# TCL File Generated by Component Editor 12.1
# Fri May 10 11:22:43 BST 2013
# DO NOT MODIFY


# 
# AvalonSampler "Avalon Sampler" v1.0
# Philip Withnall 2013.05.10.11:22:43
# Request/Response statistical sampler for Avalon memory buses.
# 

# 
# request TCL package from ACDS 12.1
# 
package require -exact qsys 12.1


# 
# module AvalonSampler
# 
set_module_property DESCRIPTION "Request/Response statistical sampler for Avalon memory buses."
set_module_property NAME AvalonSampler
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Cheri_IO
set_module_property AUTHOR "Philip Withnall"
set_module_property DISPLAY_NAME "Avalon Sampler"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL mkAvalonSampler
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file mkAvalonSampler.v VERILOG PATH mkAvalonSampler.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true

add_interface_port clock CLK clk Input 1


# 
# connection point s0
# 
add_interface s0 avalon end
set_interface_property s0 addressUnits SYMBOLS
set_interface_property s0 associatedClock clock
set_interface_property s0 associatedReset reset
set_interface_property s0 bitsPerSymbol 8
set_interface_property s0 burstOnBurstBoundariesOnly false
set_interface_property s0 burstcountUnits WORDS
set_interface_property s0 explicitAddressSpan 0
set_interface_property s0 holdTime 0
set_interface_property s0 linewrapBursts false
set_interface_property s0 maximumPendingReadTransactions 8
set_interface_property s0 readLatency 0
set_interface_property s0 readWaitTime 1
set_interface_property s0 setupTime 0
set_interface_property s0 timingUnits Cycles
set_interface_property s0 writeWaitTime 0
set_interface_property s0 ENABLED true

add_interface_port s0 avs_s0_address address Input 32
add_interface_port s0 avs_s0_writedata writedata Input 256
add_interface_port s0 avs_s0_write write Input 1
add_interface_port s0 avs_s0_read read Input 1
add_interface_port s0 avs_s0_readdata readdata Output 256
add_interface_port s0 avs_s0_waitrequest waitrequest Output 1
add_interface_port s0 avs_s0_burstcount burstcount Input 4
add_interface_port s0 avs_s0_readdatavalid readdatavalid Output 1
set_interface_assignment s0 embeddedsw.configuration.isFlash 0
set_interface_assignment s0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment s0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment s0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point m0
# 
add_interface m0 avalon start
set_interface_property m0 addressUnits SYMBOLS
set_interface_property m0 associatedClock clock
set_interface_property m0 associatedReset reset
set_interface_property m0 bitsPerSymbol 8
set_interface_property m0 burstOnBurstBoundariesOnly false
set_interface_property m0 burstcountUnits WORDS
set_interface_property m0 doStreamReads false
set_interface_property m0 doStreamWrites false
set_interface_property m0 holdTime 0
set_interface_property m0 linewrapBursts false
set_interface_property m0 maximumPendingReadTransactions 8
set_interface_property m0 readLatency 0
set_interface_property m0 readWaitTime 1
set_interface_property m0 setupTime 0
set_interface_property m0 timingUnits Cycles
set_interface_property m0 writeWaitTime 0
set_interface_property m0 ENABLED true

add_interface_port m0 avm_m0_readdata readdata Input 256
add_interface_port m0 avm_m0_waitrequest waitrequest Input 1
add_interface_port m0 avm_m0_writedata writedata Output 256
add_interface_port m0 avm_m0_address address Output 32
add_interface_port m0 avm_m0_read read Output 1
add_interface_port m0 avm_m0_write write Output 1
add_interface_port m0 avm_m0_readdatavalid readdatavalid Input 1
add_interface_port m0 avm_m0_burstcount burstcount Output 4


# 
# connection point samples_s0
# 
add_interface samples_s0 avalon end
set_interface_property samples_s0 addressUnits WORDS
set_interface_property samples_s0 associatedClock clock
set_interface_property samples_s0 associatedReset reset
set_interface_property samples_s0 bitsPerSymbol 8
set_interface_property samples_s0 burstOnBurstBoundariesOnly false
set_interface_property samples_s0 burstcountUnits WORDS
set_interface_property samples_s0 explicitAddressSpan 0
set_interface_property samples_s0 holdTime 0
set_interface_property samples_s0 linewrapBursts false
set_interface_property samples_s0 maximumPendingReadTransactions 0
set_interface_property samples_s0 readLatency 0
set_interface_property samples_s0 readWaitTime 1
set_interface_property samples_s0 setupTime 0
set_interface_property samples_s0 timingUnits Cycles
set_interface_property samples_s0 writeWaitTime 0
set_interface_property samples_s0 ENABLED true

add_interface_port samples_s0 samples_s0_address address Input 5
add_interface_port samples_s0 samples_s0_writedata writedata Input 32
add_interface_port samples_s0 samples_s0_write write Input 1
add_interface_port samples_s0 samples_s0_read read Input 1
add_interface_port samples_s0 samples_s0_readdata readdata Output 32
add_interface_port samples_s0 samples_s0_waitrequest waitrequest Output 1
set_interface_assignment samples_s0 embeddedsw.configuration.isFlash 0
set_interface_assignment samples_s0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment samples_s0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment samples_s0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true

add_interface_port reset RST_N reset_n Input 1

