# TCL File Generated by Component Editor 13.0sp1
# Thu Mar 27 14:03:47 GMT 2014
# DO NOT MODIFY


# 
# BERI_AXI "BERI_AXI" v1.0
#  2014.03.27.14:03:47
# 
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module BERI_AXI
# 
set ip_subdir [lindex [split [pwd] '/'] end]
set has_trace [string match *_trace* $ip_subdir]
set name [string toupper $ip_subdir]
set_module_property NAME $name
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP BERI_Processors
set_module_property DISPLAY_NAME $name
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE false
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL mkTopAxi
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set verilog_files [glob -tails *.v]
foreach file $verilog_files {
	add_fileset_file $file VERILOG PATH $file
}
foreach file [glob -tails *.hex] {
    add_fileset_file $file HEX PATH $file
}

# 
# parameters
# 


# 
# display items
# 


# 
# connection point interrupt_receiver
# 
add_interface interrupt_receiver interrupt start
set_interface_property interrupt_receiver associatedAddressablePoint ""
set_interface_property interrupt_receiver irqScheme INDIVIDUAL_REQUESTS
set_interface_property interrupt_receiver ENABLED true
set_interface_property interrupt_receiver EXPORT_OF ""
set_interface_property interrupt_receiver PORT_NAME_MAP ""
set_interface_property interrupt_receiver SVD_ADDRESS_GROUP ""

add_interface_port interrupt_receiver irq_irqs irq Input 32


# 
# connection point debug_source
# 
add_interface debug_source avalon_streaming start
set_interface_property debug_source associatedClock clock
set_interface_property debug_source associatedReset reset_n_in
set_interface_property debug_source dataBitsPerSymbol 8
set_interface_property debug_source errorDescriptor ""
set_interface_property debug_source firstSymbolInHighOrderBits true
set_interface_property debug_source maxChannel 0
set_interface_property debug_source readyLatency 0
set_interface_property debug_source ENABLED true
set_interface_property debug_source EXPORT_OF ""
set_interface_property debug_source PORT_NAME_MAP ""
set_interface_property debug_source SVD_ADDRESS_GROUP ""

add_interface_port debug_source debug_stream_sources_0_stream_out_data data Output 8
add_interface_port debug_source debug_stream_sources_0_stream_out_valid valid Output 1
add_interface_port debug_source debug_stream_sources_0_stream_out_ready ready Input 1


# 
# connection point debug_sink
# 
add_interface debug_sink avalon_streaming end
set_interface_property debug_sink associatedClock clock
set_interface_property debug_sink associatedReset reset_n_in
set_interface_property debug_sink dataBitsPerSymbol 8
set_interface_property debug_sink errorDescriptor ""
set_interface_property debug_sink firstSymbolInHighOrderBits true
set_interface_property debug_sink maxChannel 0
set_interface_property debug_sink readyLatency 0
set_interface_property debug_sink ENABLED true
set_interface_property debug_sink EXPORT_OF ""
set_interface_property debug_sink PORT_NAME_MAP ""
set_interface_property debug_sink SVD_ADDRESS_GROUP ""

add_interface_port debug_sink debug_stream_sinks_0_stream_in_data data Input 8
add_interface_port debug_sink debug_stream_sinks_0_stream_in_valid valid Input 1
add_interface_port debug_sink debug_stream_sinks_0_stream_in_ready ready Output 1


# 
# connection point memory_master
# 
add_interface memory_master axi start
set_interface_property memory_master associatedClock clock
set_interface_property memory_master associatedReset reset_n_in
set_interface_property memory_master readIssuingCapability 4
set_interface_property memory_master writeIssuingCapability 4
set_interface_property memory_master combinedIssuingCapability 4
set_interface_property memory_master ENABLED true
set_interface_property memory_master EXPORT_OF ""
set_interface_property memory_master PORT_NAME_MAP ""
set_interface_property memory_master SVD_ADDRESS_GROUP ""

add_interface_port memory_master axm_memory_AWID awid Output 8
add_interface_port memory_master axm_memory_AWADDR awaddr Output 40
add_interface_port memory_master axm_memory_WSTRB wstrb Output 16
add_interface_port memory_master axm_memory_ARSIZE arsize Output 3
add_interface_port memory_master axm_memory_RLAST rlast Input 1
add_interface_port memory_master axm_memory_AWLEN awlen Output 4
add_interface_port memory_master axm_memory_AWSIZE awsize Output 3
add_interface_port memory_master axm_memory_WVALID wvalid Output 1
add_interface_port memory_master axm_memory_ARLOCK arlock Output 2
add_interface_port memory_master axm_memory_AWBURST awburst Output 2
add_interface_port memory_master axm_memory_WREADY wready Input 1
add_interface_port memory_master axm_memory_ARCACHE arcache Output 4
add_interface_port memory_master axm_memory_AWLOCK awlock Output 2
add_interface_port memory_master axm_memory_BREADY bready Output 1
add_interface_port memory_master axm_memory_ARPROT arprot Output 3
add_interface_port memory_master axm_memory_AWCACHE awcache Output 4
add_interface_port memory_master axm_memory_BID bid Input 8
add_interface_port memory_master axm_memory_ARVALID arvalid Output 1
add_interface_port memory_master axm_memory_AWPROT awprot Output 3
add_interface_port memory_master axm_memory_BRESP bresp Input 2
add_interface_port memory_master axm_memory_ARREADY arready Input 1
add_interface_port memory_master axm_memory_BVALID bvalid Input 1
add_interface_port memory_master axm_memory_RREADY rready Output 1
add_interface_port memory_master axm_memory_AWVALID awvalid Output 1
add_interface_port memory_master axm_memory_AWREADY awready Input 1
add_interface_port memory_master axm_memory_ARID arid Output 8
add_interface_port memory_master axm_memory_RID rid Input 8
add_interface_port memory_master axm_memory_WID wid Output 8
add_interface_port memory_master axm_memory_ARADDR araddr Output 40
add_interface_port memory_master axm_memory_RDATA rdata Input 128
add_interface_port memory_master axm_memory_WDATA wdata Output 128
add_interface_port memory_master axm_memory_ARLEN arlen Output 4
add_interface_port memory_master axm_memory_RRESP rresp Input 2
add_interface_port memory_master axm_memory_WLAST wlast Output 1
add_interface_port memory_master axm_memory_ARBURST arburst Output 2
add_interface_port memory_master axm_memory_RVALID rvalid Input 1


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 100000000
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock csi_clockreset_clk clk Input 1


# 
# connection point reset_n_in
# 
add_interface reset_n_in reset end
set_interface_property reset_n_in associatedClock clock
set_interface_property reset_n_in synchronousEdges DEASSERT
set_interface_property reset_n_in ENABLED true
set_interface_property reset_n_in EXPORT_OF ""
set_interface_property reset_n_in PORT_NAME_MAP ""
set_interface_property reset_n_in SVD_ADDRESS_GROUP ""

add_interface_port reset_n_in csi_clockreset_reset_n reset_n Input 1


# 
# connection point reset_n_out
# 
add_interface reset_n_out reset start
set_interface_property reset_n_out associatedClock clock
set_interface_property reset_n_out associatedDirectReset ""
set_interface_property reset_n_out associatedResetSinks ""
set_interface_property reset_n_out synchronousEdges DEASSERT
set_interface_property reset_n_out ENABLED true
set_interface_property reset_n_out EXPORT_OF ""
set_interface_property reset_n_out PORT_NAME_MAP ""
set_interface_property reset_n_out SVD_ADDRESS_GROUP ""

add_interface_port reset_n_out reset_n_out reset_n Output 1

