#!/bin/sh
#-
# Copyright (c) 2012-2013 SRI International
# Copyright (c) 2014 Bjoern A. Zeeb
# All rights reserved.
#
# This software was developed by SRI International and the University of
# Cambridge Computer Laboratory under DARPA/AFRL contract FA8750-10-C-0237
# ("CTSRD"), as part of the DARPA CRASH research programme.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#

if [ -e /dev/led/de4led_0 ]; then
	echo f9 > /dev/led/de4led_0
fi

# If we aren't using an SDCARD root and an SDCARD is present
# then mount it and see if it contains upgrades.
SDCARD=/dev/altera_sdcard0
tmp=`mount | grep ${SDCARD#/dev/}`
mounted=
if [ -z "${tmp}" -a -c ${SDCARD} ]; then
	if mount -t ufs -o ro ${SDCARD} /upgrades; then
		if [ ! -r /upgrades/upgrade.sh ]; then
			umount /upgrades
		else
			mounted=yes
		fi
	fi
fi
# See if we have upgrades to install
if [ -r /upgrades/upgrade.sh ]; then
	/usr/sbin/mtlctl fbloadpng /usr/share/images/upgrade-inprogress.png

	# Try to mount /tmp since we will need it for compressed files.
	mount /tmp

	if sh /upgrades/upgrade.sh; then
		/usr/sbin/mtlctl fbloadpng /usr/share/images/upgrade-complete.png
		# sleep forever
		while true; do
			sleep 60
		done
	fi
fi
if [ -n "${mounted}" ]; then
	umount /upgrades
fi
if [ -x /usr/sbin/mtlctl ]; then
	/usr/sbin/mtlctl fbloadpng /usr/share/images/booting.png
fi
