#-
# Copyright (c) 2014 Alexandre Joannou
# Copyright (c) 2014 Alan Mujumdar
# All rights reserved.
#
# This software was developed by SRI International and the University of
# Cambridge Computer Laboratory under DARPA/AFRL contract FA8750-10-C-0237
# ("CTSRD"), as part of the DARPA CRASH research programme.
#
# This software was developed by SRI International and the University of
# Cambridge Computer Laboratory under DARPA/AFRL contract FA8750-11-C-0249
# ("MRC2"), as part of the DARPA MRC research programme.
#
# @BERI_LICENSE_HEADER_START@
#
# Licensed to BERI Open Systems C.I.C (BERI) under one or more contributor
# license agreements.  See the NOTICE file distributed with this work for
# additional information regarding copyright ownership.  BERI licenses this
# file to you under the BERI Hardware-Software License, Version 1.0 (the
# "License"); you may not use this file except in compliance with the
# License.  You may obtain a copy of the License at:
#
#   http://www.beri-open-systems.org/legal/license-1-0.txt
#
# Unless required by applicable law or agreed to in writing, Work distributed
# under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
# CONDITIONS OF ANY KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations under the License.
#
# @BERI_LICENSE_HEADER_END@
#

LIB_DIR ?= ../../libs
OBJ_DIR ?= ../../obj

CC = mips-linux-gnu-gcc
AS = mips64-as
LD = mips-linux-gnu-ld
OBJCOPY = mips-linux-gnu-objcopy
OBJDUMP = mips64-objdump

.PHONY : clean obj_file

obj_file : parallel_sort.c parallel_sort.h
	mkdir -p $(OBJ_DIR)
	$(CC) -march=mips64 -mabi=64 -S -c -I $(LIB_DIR) -o $(OBJ_DIR)/$(patsubst %.c,%.s,$<) $<
	$(AS) -EB -march=mips64 -mabi=64 -G0 -ggdb -o $(OBJ_DIR)/$(patsubst %.c,%.o,$<) $(OBJ_DIR)/$(patsubst %.c,%.s,$<)
	$(OBJDUMP) -xsSd $(OBJ_DIR)/$(patsubst %.c,%.o,$<) > $(OBJ_DIR)/$(patsubst %.c,%.dump,$<)

clean :
	rm -f $(OBJ_DIR)/scatter_gather.o
	rm -f $(OBJ_DIR)/scatter_gather.s
	rm -f $(OBJ_DIR)/scatter_gather.dump
