# TCL File Generated by Component Editor 13.1
# Tue Aug 26 12:05:42 BST 2014
# DO NOT MODIFY


# 
# USB1761Bridge "USB1761Bridge" v1.0
#  2014.08.26.12:05:42
# 
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module USB1761Bridge
# 
set_module_property DESCRIPTION ""
set_module_property NAME USB1761Bridge
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Cheri_IO
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME USB1761Bridge
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL mkUSB1761Bridge
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file mkUSB1761Bridge.v VERILOG PATH mkUSB1761Bridge.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clockreset
# 
add_interface clockreset clock end
set_interface_property clockreset clockRate 0
set_interface_property clockreset ENABLED true
set_interface_property clockreset EXPORT_OF ""
set_interface_property clockreset PORT_NAME_MAP ""
set_interface_property clockreset CMSIS_SVD_VARIABLES ""
set_interface_property clockreset SVD_ADDRESS_GROUP ""

add_interface_port clockreset csi_clockreset_clk clk Input 1


# 
# connection point clockreset_reset
# 
add_interface clockreset_reset reset end
set_interface_property clockreset_reset associatedClock clockreset
set_interface_property clockreset_reset synchronousEdges DEASSERT
set_interface_property clockreset_reset ENABLED true
set_interface_property clockreset_reset EXPORT_OF ""
set_interface_property clockreset_reset PORT_NAME_MAP ""
set_interface_property clockreset_reset CMSIS_SVD_VARIABLES ""
set_interface_property clockreset_reset SVD_ADDRESS_GROUP ""

add_interface_port clockreset_reset csi_clockreset_reset_n reset_n Input 1


# 
# connection point s0
# 
add_interface s0 avalon end
set_interface_property s0 addressUnits WORDS
set_interface_property s0 associatedClock clockreset
set_interface_property s0 associatedReset clockreset_reset
set_interface_property s0 bitsPerSymbol 8
set_interface_property s0 burstOnBurstBoundariesOnly false
set_interface_property s0 burstcountUnits WORDS
set_interface_property s0 explicitAddressSpan 0
set_interface_property s0 holdTime 0
set_interface_property s0 linewrapBursts false
set_interface_property s0 maximumPendingReadTransactions 0
set_interface_property s0 readLatency 0
set_interface_property s0 readWaitTime 1
set_interface_property s0 setupTime 0
set_interface_property s0 timingUnits Cycles
set_interface_property s0 writeWaitTime 0
set_interface_property s0 ENABLED true
set_interface_property s0 EXPORT_OF ""
set_interface_property s0 PORT_NAME_MAP ""
set_interface_property s0 CMSIS_SVD_VARIABLES ""
set_interface_property s0 SVD_ADDRESS_GROUP ""

add_interface_port s0 avs_s0_address address Input 16
add_interface_port s0 avs_s0_writedata writedata Input 32
add_interface_port s0 avs_s0_write write Input 1
add_interface_port s0 avs_s0_read read Input 1
add_interface_port s0 avs_s0_readdata readdata Output 32
add_interface_port s0 avs_s0_waitrequest waitrequest Output 1
set_interface_assignment s0 embeddedsw.configuration.isFlash 0
set_interface_assignment s0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment s0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment s0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point conduit_end_0
# 
add_interface conduit_end_0 conduit end
set_interface_property conduit_end_0 associatedClock clockreset
set_interface_property conduit_end_0 associatedReset ""
set_interface_property conduit_end_0 ENABLED true
set_interface_property conduit_end_0 EXPORT_OF ""
set_interface_property conduit_end_0 PORT_NAME_MAP ""
set_interface_property conduit_end_0 CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end_0 SVD_ADDRESS_GROUP ""

add_interface_port conduit_end_0 coe_cs_n coe_cs_n Output 1
add_interface_port conduit_end_0 coe_rd_n coe_rd_n Output 1
add_interface_port conduit_end_0 coe_dout_din coe_din Input 32
add_interface_port conduit_end_0 coe_dout coe_dout Output 32
add_interface_port conduit_end_0 coe_a coe_a Output 17
add_interface_port conduit_end_0 coe_dc_irq_in coe_dc_irq_in Input 1
add_interface_port conduit_end_0 coe_hc_irq_in coe_hc_irq_in Input 1
add_interface_port conduit_end_0 coe_wr_n coe_wr_n Output 1


# 
# connection point hc
# 
add_interface hc interrupt end
set_interface_property hc associatedAddressablePoint ""
set_interface_property hc associatedClock clockreset
set_interface_property hc associatedReset clockreset_reset
set_interface_property hc ENABLED true
set_interface_property hc EXPORT_OF ""
set_interface_property hc PORT_NAME_MAP ""
set_interface_property hc CMSIS_SVD_VARIABLES ""
set_interface_property hc SVD_ADDRESS_GROUP ""

add_interface_port hc coe_hc_irq irq_n Output 1


# 
# connection point dc
# 
add_interface dc interrupt end
set_interface_property dc associatedAddressablePoint ""
set_interface_property dc associatedClock clockreset
set_interface_property dc associatedReset clockreset_reset
set_interface_property dc ENABLED true
set_interface_property dc EXPORT_OF ""
set_interface_property dc PORT_NAME_MAP ""
set_interface_property dc CMSIS_SVD_VARIABLES ""
set_interface_property dc SVD_ADDRESS_GROUP ""

add_interface_port dc coe_dc_irq irq_n Output 1

