# TCL File Generated by Component Editor 12.1
# Tue Mar 12 18:32:22 GMT 2013
# DO NOT MODIFY


# 
# CompositorPhy "Graphics Compositor" v1.0
# Philip Withnall 2013.03.12.18:32:22
# 2D graphics compositor
# 

# 
# request TCL package from ACDS 12.1
# 
package require -exact qsys 12.1


# 
# module CompositorPhy
# 
set_module_property DESCRIPTION "2D graphics compositor"
set_module_property NAME CompositorPhy
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Cheri_Video
set_module_property AUTHOR "Philip Withnall"
set_module_property DISPLAY_NAME "Graphics Compositor"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL mkCompositorPhy
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file mkCompositorPhy.v VERILOG PATH mkCompositorPhy.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true

add_interface_port clock CLK clk Input 1


# 
# connection point extcontrol_s0
# 
add_interface extcontrol_s0 avalon end
set_interface_property extcontrol_s0 addressUnits WORDS
set_interface_property extcontrol_s0 associatedClock clock
set_interface_property extcontrol_s0 associatedReset reset
set_interface_property extcontrol_s0 bitsPerSymbol 8
set_interface_property extcontrol_s0 burstOnBurstBoundariesOnly false
set_interface_property extcontrol_s0 burstcountUnits WORDS
set_interface_property extcontrol_s0 explicitAddressSpan 0
set_interface_property extcontrol_s0 holdTime 0
set_interface_property extcontrol_s0 linewrapBursts false
set_interface_property extcontrol_s0 maximumPendingReadTransactions 0
set_interface_property extcontrol_s0 readLatency 0
set_interface_property extcontrol_s0 readWaitTime 1
set_interface_property extcontrol_s0 setupTime 0
set_interface_property extcontrol_s0 timingUnits Cycles
set_interface_property extcontrol_s0 writeWaitTime 0
set_interface_property extcontrol_s0 ENABLED true

add_interface_port extcontrol_s0 extControl_s0_address address Input 6
add_interface_port extcontrol_s0 extControl_s0_writedata writedata Input 32
add_interface_port extcontrol_s0 extControl_s0_write write Input 1
add_interface_port extcontrol_s0 extControl_s0_read read Input 1
add_interface_port extcontrol_s0 extControl_s0_readdata readdata Output 32
add_interface_port extcontrol_s0 extControl_s0_waitrequest waitrequest Output 1
set_interface_assignment extcontrol_s0 embeddedsw.configuration.isFlash 0
set_interface_assignment extcontrol_s0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment extcontrol_s0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment extcontrol_s0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point pixelsout_stream_out
# 
add_interface pixelsout_stream_out avalon_streaming start
set_interface_property pixelsout_stream_out associatedClock clock
set_interface_property pixelsout_stream_out associatedReset reset
set_interface_property pixelsout_stream_out dataBitsPerSymbol 24
set_interface_property pixelsout_stream_out errorDescriptor ""
set_interface_property pixelsout_stream_out firstSymbolInHighOrderBits true
set_interface_property pixelsout_stream_out maxChannel 0
set_interface_property pixelsout_stream_out readyLatency 0
set_interface_property pixelsout_stream_out ENABLED true

add_interface_port pixelsout_stream_out pixelsOut_stream_out_endofpacket endofpacket Output 1
add_interface_port pixelsout_stream_out pixelsOut_stream_out_startofpacket startofpacket Output 1
add_interface_port pixelsout_stream_out pixelsOut_stream_out_ready ready Input 1
add_interface_port pixelsout_stream_out pixelsOut_stream_out_valid valid Output 1
add_interface_port pixelsout_stream_out pixelsOut_stream_out_data data Output 24


# 
# connection point extmemory_m0
# 
add_interface extmemory_m0 avalon start
set_interface_property extmemory_m0 addressUnits SYMBOLS
set_interface_property extmemory_m0 associatedClock clock
set_interface_property extmemory_m0 associatedReset reset
set_interface_property extmemory_m0 bitsPerSymbol 8
set_interface_property extmemory_m0 burstOnBurstBoundariesOnly false
set_interface_property extmemory_m0 burstcountUnits WORDS
set_interface_property extmemory_m0 doStreamReads false
set_interface_property extmemory_m0 doStreamWrites false
set_interface_property extmemory_m0 holdTime 0
set_interface_property extmemory_m0 linewrapBursts false
set_interface_property extmemory_m0 maximumPendingReadTransactions 0
set_interface_property extmemory_m0 readLatency 0
set_interface_property extmemory_m0 readWaitTime 1
set_interface_property extmemory_m0 setupTime 0
set_interface_property extmemory_m0 timingUnits Cycles
set_interface_property extmemory_m0 writeWaitTime 0
set_interface_property extmemory_m0 ENABLED true

add_interface_port extmemory_m0 extMemory_m0_readdata readdata Input 256
add_interface_port extmemory_m0 extMemory_m0_readdatavalid readdatavalid Input 1
add_interface_port extmemory_m0 extMemory_m0_waitrequest waitrequest Input 1
add_interface_port extmemory_m0 extMemory_m0_writedata writedata Output 256
add_interface_port extmemory_m0 extMemory_m0_address address Output 32
add_interface_port extmemory_m0 extMemory_m0_read read Output 1
add_interface_port extmemory_m0 extMemory_m0_write write Output 1
add_interface_port extmemory_m0 extMemory_m0_burstcount burstcount Output 4


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true

add_interface_port reset RST_N reset_n Input 1

