# TCL File Generated by Component Editor 12.1
# Sun Feb 10 20:34:56 GMT 2013
# DO NOT MODIFY


# 
# mkHDMI_Driver "HDMI driver reconfigurable" v1.0
# Simon Moore 2013.02.10.20:34:56
# HDMI hsync and vsync timing (parameterisable)
# 

# 
# request TCL package from ACDS 12.1
# 
package require -exact qsys 12.1


# 
# module mkHDMI_Driver
# 
set_module_property DESCRIPTION "HDMI hsync and vsync timing (parameterisable)"
set_module_property NAME mkHDMI_Driver
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Cheri_Video
set_module_property AUTHOR "Simon Moore"
set_module_property DISPLAY_NAME "HDMI driver reconfigurable"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL mkHDMI_Driver
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file mkHDMI_Driver.v VERILOG PATH mkHDMI_Driver.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clockreset
# 
add_interface clockreset clock end
set_interface_property clockreset clockRate 0
set_interface_property clockreset ENABLED true

add_interface_port clockreset csi_clockreset_clk clk Input 1


# 
# connection point clockreset_reset
# 
add_interface clockreset_reset reset end
set_interface_property clockreset_reset associatedClock clockreset
set_interface_property clockreset_reset synchronousEdges DEASSERT
set_interface_property clockreset_reset ENABLED true

add_interface_port clockreset_reset csi_clockreset_reset_n reset_n Input 1


# 
# connection point pixel_stream_in
# 
add_interface pixel_stream_in avalon_streaming end
set_interface_property pixel_stream_in associatedClock clockreset
set_interface_property pixel_stream_in associatedReset clockreset_reset
set_interface_property pixel_stream_in dataBitsPerSymbol 8
set_interface_property pixel_stream_in errorDescriptor ""
set_interface_property pixel_stream_in firstSymbolInHighOrderBits true
set_interface_property pixel_stream_in maxChannel 0
set_interface_property pixel_stream_in readyLatency 0
set_interface_property pixel_stream_in ENABLED true

add_interface_port pixel_stream_in asi_stream_in_data data Input 24
add_interface_port pixel_stream_in asi_stream_in_valid valid Input 1
add_interface_port pixel_stream_in asi_stream_in_startofpacket startofpacket Input 1
add_interface_port pixel_stream_in asi_stream_in_endofpacket endofpacket Input 1
add_interface_port pixel_stream_in asi_stream_in_ready ready Output 1


# 
# connection point avalonmm_slave
# 
add_interface avalonmm_slave avalon end
set_interface_property avalonmm_slave addressUnits WORDS
set_interface_property avalonmm_slave associatedClock clockreset
set_interface_property avalonmm_slave associatedReset clockreset_reset
set_interface_property avalonmm_slave bitsPerSymbol 8
set_interface_property avalonmm_slave burstOnBurstBoundariesOnly false
set_interface_property avalonmm_slave burstcountUnits WORDS
set_interface_property avalonmm_slave explicitAddressSpan 0
set_interface_property avalonmm_slave holdTime 0
set_interface_property avalonmm_slave linewrapBursts false
set_interface_property avalonmm_slave maximumPendingReadTransactions 0
set_interface_property avalonmm_slave readLatency 0
set_interface_property avalonmm_slave readWaitTime 1
set_interface_property avalonmm_slave setupTime 0
set_interface_property avalonmm_slave timingUnits Cycles
set_interface_property avalonmm_slave writeWaitTime 0
set_interface_property avalonmm_slave ENABLED true

add_interface_port avalonmm_slave avs_s0_address address Input 3
add_interface_port avalonmm_slave avs_s0_writedata writedata Input 32
add_interface_port avalonmm_slave avs_s0_write write Input 1
add_interface_port avalonmm_slave avs_s0_read read Input 1
add_interface_port avalonmm_slave avs_s0_readdata readdata Output 32
add_interface_port avalonmm_slave avs_s0_waitrequest waitrequest Output 1
set_interface_assignment avalonmm_slave embeddedsw.configuration.isFlash 0
set_interface_assignment avalonmm_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalonmm_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalonmm_slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point conduit_hdmi
# 
add_interface conduit_hdmi conduit end
set_interface_property conduit_hdmi associatedClock clockreset
set_interface_property conduit_hdmi associatedReset clockreset_reset
set_interface_property conduit_hdmi ENABLED true

add_interface_port conduit_hdmi coe_hdmi_r export Output 12
add_interface_port conduit_hdmi coe_hdmi_g export Output 12
add_interface_port conduit_hdmi coe_hdmi_b export Output 12
add_interface_port conduit_hdmi coe_hdmi_hsd export Output 1
add_interface_port conduit_hdmi coe_hdmi_vsd export Output 1
add_interface_port conduit_hdmi coe_hdmi_de export Output 1


# 
# connection point conduit_resolution
# 
add_interface conduit_resolution conduit end
set_interface_property conduit_resolution associatedClock clockreset
set_interface_property conduit_resolution associatedReset clockreset_reset
set_interface_property conduit_resolution ENABLED true

add_interface_port conduit_resolution coe_resolution_xres export Output 12
add_interface_port conduit_resolution coe_resolution_yres export Output 12

