# TCL File Generated by Component Editor 12.1
# Sun Feb 10 20:53:53 GMT 2013
# DO NOT MODIFY


# 
# mkHDMIVideoTestSource "HDMI Video Test Source" v1.0
# Simon Moore 2013.02.10.20:53:53
# Parameterised video test source for HDMI output
# 

# 
# request TCL package from ACDS 12.1
# 
package require -exact qsys 12.1


# 
# module mkHDMIVideoTestSource
# 
set_module_property DESCRIPTION "Parameterised video test source for HDMI output"
set_module_property NAME mkHDMIVideoTestSource
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Cheri_Video
set_module_property AUTHOR "Simon Moore"
set_module_property DISPLAY_NAME "HDMI Video Test Source"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL mkHDMIVideoTestSource
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file mkHDMIVideoTestSource.v VERILOG PATH mkHDMIVideoTestSource.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clockreset
# 
add_interface clockreset clock end
set_interface_property clockreset clockRate 0
set_interface_property clockreset ENABLED true

add_interface_port clockreset csi_clockreset_clk clk Input 1


# 
# connection point clockreset_reset
# 
add_interface clockreset_reset reset end
set_interface_property clockreset_reset associatedClock clockreset
set_interface_property clockreset_reset synchronousEdges DEASSERT
set_interface_property clockreset_reset ENABLED true

add_interface_port clockreset_reset csi_clockreset_reset_n reset_n Input 1


# 
# connection point pixel_stream_out
# 
add_interface pixel_stream_out avalon_streaming start
set_interface_property pixel_stream_out associatedClock clockreset
set_interface_property pixel_stream_out associatedReset clockreset_reset
set_interface_property pixel_stream_out dataBitsPerSymbol 8
set_interface_property pixel_stream_out errorDescriptor ""
set_interface_property pixel_stream_out firstSymbolInHighOrderBits true
set_interface_property pixel_stream_out maxChannel 0
set_interface_property pixel_stream_out readyLatency 0
set_interface_property pixel_stream_out ENABLED true

add_interface_port pixel_stream_out aso_stream_out_data data Output 24
add_interface_port pixel_stream_out aso_stream_out_valid valid Output 1
add_interface_port pixel_stream_out aso_stream_out_ready ready Input 1
add_interface_port pixel_stream_out aso_stream_out_startofpacket startofpacket Output 1
add_interface_port pixel_stream_out aso_stream_out_endofpacket endofpacket Output 1


# 
# connection point conduit_resolution_in
# 
add_interface conduit_resolution_in conduit end
set_interface_property conduit_resolution_in associatedClock clockreset
set_interface_property conduit_resolution_in associatedReset clockreset_reset
set_interface_property conduit_resolution_in ENABLED true

add_interface_port conduit_resolution_in coe_resolution_xres export Input 12
add_interface_port conduit_resolution_in coe_resolution_yres export Input 12

