# TCL File Generated by Component Editor 13.1
# Tue May 13 15:10:31 BST 2014
# DO NOT MODIFY


# 
# pcie_stream_in "PCI Express Stream In" v1.0
#  2014.05.13.15:10:31
# 
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module pcie_stream_in
# 
set_module_property DESCRIPTION ""
set_module_property NAME pcie_stream_in
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "PCI Express Stream In"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL mkPCIStreamIn
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file mkPCIStreamIn.v VERILOG PATH ./mkPCIStreamIn.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock csi_clk clk Input 1


# 
# connection point clock_reset
# 
add_interface clock_reset reset end
set_interface_property clock_reset associatedClock clock
set_interface_property clock_reset synchronousEdges DEASSERT
set_interface_property clock_reset ENABLED true
set_interface_property clock_reset EXPORT_OF ""
set_interface_property clock_reset PORT_NAME_MAP ""
set_interface_property clock_reset CMSIS_SVD_VARIABLES ""
set_interface_property clock_reset SVD_ADDRESS_GROUP ""

add_interface_port clock_reset csi_reset_n reset_n Input 1


# 
# connection point aso
# 
add_interface aso avalon_streaming start
set_interface_property aso associatedClock clock
set_interface_property aso associatedReset clock_reset
set_interface_property aso dataBitsPerSymbol 8
set_interface_property aso errorDescriptor ""
set_interface_property aso firstSymbolInHighOrderBits true
set_interface_property aso maxChannel 0
set_interface_property aso readyLatency 0
set_interface_property aso ENABLED true
set_interface_property aso EXPORT_OF ""
set_interface_property aso PORT_NAME_MAP ""
set_interface_property aso CMSIS_SVD_VARIABLES ""
set_interface_property aso SVD_ADDRESS_GROUP ""

add_interface_port aso aso_aso_ready ready Input 1
add_interface_port aso aso_aso_data data Output 8
add_interface_port aso aso_aso_valid valid Output 1


# 
# connection point ctrl_avs
# 
add_interface ctrl_avs avalon end
set_interface_property ctrl_avs addressUnits WORDS
set_interface_property ctrl_avs associatedClock clock
set_interface_property ctrl_avs associatedReset clock_reset
set_interface_property ctrl_avs bitsPerSymbol 8
set_interface_property ctrl_avs burstOnBurstBoundariesOnly false
set_interface_property ctrl_avs burstcountUnits WORDS
set_interface_property ctrl_avs explicitAddressSpan 0
set_interface_property ctrl_avs holdTime 0
set_interface_property ctrl_avs linewrapBursts false
set_interface_property ctrl_avs maximumPendingReadTransactions 1
set_interface_property ctrl_avs readLatency 0
set_interface_property ctrl_avs readWaitTime 1
set_interface_property ctrl_avs setupTime 0
set_interface_property ctrl_avs timingUnits Cycles
set_interface_property ctrl_avs writeWaitTime 0
set_interface_property ctrl_avs ENABLED true
set_interface_property ctrl_avs EXPORT_OF ""
set_interface_property ctrl_avs PORT_NAME_MAP ""
set_interface_property ctrl_avs CMSIS_SVD_VARIABLES ""
set_interface_property ctrl_avs SVD_ADDRESS_GROUP ""

add_interface_port ctrl_avs avs_ctrl_avs_readdata readdata Output 64
add_interface_port ctrl_avs avs_ctrl_avs_readdatavalid readdatavalid Output 1
add_interface_port ctrl_avs avs_ctrl_avs_waitrequest waitrequest Output 1
add_interface_port ctrl_avs avs_ctrl_avs_writedata writedata Input 64
add_interface_port ctrl_avs avs_ctrl_avs_address address Input 1
add_interface_port ctrl_avs avs_ctrl_avs_read read Input 1
add_interface_port ctrl_avs avs_ctrl_avs_write write Input 1
set_interface_assignment ctrl_avs embeddedsw.configuration.isFlash 0
set_interface_assignment ctrl_avs embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment ctrl_avs embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment ctrl_avs embeddedsw.configuration.isPrintableDevice 0


# 
# connection point buf_avs
# 
add_interface buf_avs avalon end
set_interface_property buf_avs addressUnits WORDS
set_interface_property buf_avs associatedClock clock
set_interface_property buf_avs associatedReset clock_reset
set_interface_property buf_avs bitsPerSymbol 8
set_interface_property buf_avs burstOnBurstBoundariesOnly false
set_interface_property buf_avs burstcountUnits WORDS
set_interface_property buf_avs explicitAddressSpan 0
set_interface_property buf_avs holdTime 0
set_interface_property buf_avs linewrapBursts false
set_interface_property buf_avs maximumPendingReadTransactions 1
set_interface_property buf_avs readLatency 0
set_interface_property buf_avs readWaitTime 1
set_interface_property buf_avs setupTime 0
set_interface_property buf_avs timingUnits Cycles
set_interface_property buf_avs writeWaitTime 0
set_interface_property buf_avs ENABLED true
set_interface_property buf_avs EXPORT_OF ""
set_interface_property buf_avs PORT_NAME_MAP ""
set_interface_property buf_avs CMSIS_SVD_VARIABLES ""
set_interface_property buf_avs SVD_ADDRESS_GROUP ""

add_interface_port buf_avs avs_buf_avs_readdata readdata Output 64
add_interface_port buf_avs avs_buf_avs_readdatavalid readdatavalid Output 1
add_interface_port buf_avs avs_buf_avs_waitrequest waitrequest Output 1
add_interface_port buf_avs avs_buf_avs_writedata writedata Input 64
add_interface_port buf_avs avs_buf_avs_address address Input 13
add_interface_port buf_avs avs_buf_avs_read read Input 1
add_interface_port buf_avs avs_buf_avs_write write Input 1
add_interface_port buf_avs avs_buf_avs_byteenable byteenable Input 8
set_interface_assignment buf_avs embeddedsw.configuration.isFlash 0
set_interface_assignment buf_avs embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment buf_avs embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment buf_avs embeddedsw.configuration.isPrintableDevice 0

