# TCL File Generated by Component Editor 12.1
# Sun Feb 10 18:27:05 GMT 2013
# DO NOT MODIFY


# 
# video_pll_reconfig_avalonmm "Video PLL reconfiguration interface" v1.0
# Simon Moore 2013.02.10.18:27:05
# 
# 

# 
# request TCL package from ACDS 12.1
# 
package require -exact qsys 12.1


# 
# module video_pll_reconfig_avalonmm
# 
set_module_property NAME video_pll_reconfig_avalonmm
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Cheri_Video
set_module_property AUTHOR "Simon Moore"
set_module_property DISPLAY_NAME "Video PLL reconfiguration interface"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL video_pll_config_avalonmm
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file video_pll_reconfig_avalonmm.sv SYSTEM_VERILOG PATH video_pll_reconfig_avalonmm.sv
add_fileset_file video_pll_reconfig.v VERILOG PATH video_pll_reconfig.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true

add_interface_port clock csi_clk_clock clk Input 1


# 
# connection point clk_reset
# 
add_interface clk_reset reset end
set_interface_property clk_reset associatedClock clock
set_interface_property clk_reset synchronousEdges DEASSERT
set_interface_property clk_reset ENABLED true

add_interface_port clk_reset csi_clk_reset reset Input 1


# 
# connection point avalon_slave
# 
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressUnits WORDS
set_interface_property avalon_slave associatedClock clock
set_interface_property avalon_slave associatedReset clk_reset
set_interface_property avalon_slave bitsPerSymbol 8
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave burstcountUnits WORDS
set_interface_property avalon_slave explicitAddressSpan 0
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 0
set_interface_property avalon_slave readLatency 0
set_interface_property avalon_slave readWaitTime 1
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave writeWaitTime 0
set_interface_property avalon_slave ENABLED true

add_interface_port avalon_slave avs_address address Input 8
add_interface_port avalon_slave avs_writedata writedata Input 32
add_interface_port avalon_slave avs_readdata readdata Output 32
add_interface_port avalon_slave avs_read read Input 1
add_interface_port avalon_slave avs_write write Input 1
add_interface_port avalon_slave avs_waitrequest waitrequest Output 1
set_interface_assignment avalon_slave embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point conduit_reconfig_pll
# 
add_interface conduit_reconfig_pll conduit end
set_interface_property conduit_reconfig_pll associatedClock clock
set_interface_property conduit_reconfig_pll associatedReset clk_reset
set_interface_property conduit_reconfig_pll ENABLED true

add_interface_port conduit_reconfig_pll coe_pll_scandataout export Input 1
add_interface_port conduit_reconfig_pll coe_pll_scandone export Input 1
add_interface_port conduit_reconfig_pll coe_pll_areset export Output 1
add_interface_port conduit_reconfig_pll coe_pll_configupdate export Output 1
add_interface_port conduit_reconfig_pll coe_pll_scanclk export Output 1
add_interface_port conduit_reconfig_pll coe_pll_scanclkena export Output 1
add_interface_port conduit_reconfig_pll coe_pll_scandata export Output 1

