# TCL File Generated by Component Editor 12.1
# Tue Dec 04 14:41:24 GMT 2012
# DO NOT MODIFY


# 
# i2c_avalon "i2c" v1.0
# Simon Moore + OpenCores author 2012.12.04.14:41:24
# I2C interface based on OpenCores version with AvalonMM wrapper
# 

# 
# request TCL package from ACDS 12.1
# 
package require -exact qsys 12.1


# 
# module i2c_avalon
# 
set_module_property DESCRIPTION "I2C interface based on OpenCores version with AvalonMM wrapper"
set_module_property NAME i2c_avalon
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Cheri_IO
set_module_property AUTHOR "Simon Moore + OpenCores author"
set_module_property DISPLAY_NAME i2c
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset quartus_synth QUARTUS_SYNTH "" "Quartus Synthesis"
set_fileset_property quartus_synth TOP_LEVEL i2c_avalon
set_fileset_property quartus_synth ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file i2c_avalon.sv SYSTEM_VERILOG PATH i2c_avalon.sv
add_fileset_file i2c_master_bit_ctrl.v VERILOG_INCLUDE PATH i2c_master_bit_ctrl.v
add_fileset_file i2c_master_byte_ctrl.v VERILOG_INCLUDE PATH i2c_master_byte_ctrl.v
add_fileset_file i2c_master_defines.v VERILOG_INCLUDE PATH i2c_master_defines.v
add_fileset_file i2c_master_top.v VERILOG_INCLUDE PATH i2c_master_top.v
add_fileset_file i2c_timescale.v VERILOG_INCLUDE PATH i2c_timescale.v

add_fileset sim_verilog SIM_VERILOG "" "Verilog Simulation"
set_fileset_property sim_verilog TOP_LEVEL i2c_avalon
set_fileset_property sim_verilog ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file i2c_avalon.sv SYSTEM_VERILOG PATH i2c_avalon.sv
add_fileset_file i2c_master_bit_ctrl.v VERILOG_INCLUDE PATH i2c_master_bit_ctrl.v
add_fileset_file i2c_master_byte_ctrl.v VERILOG_INCLUDE PATH i2c_master_byte_ctrl.v
add_fileset_file i2c_master_defines.v VERILOG_INCLUDE PATH i2c_master_defines.v
add_fileset_file i2c_master_top.v VERILOG_INCLUDE PATH i2c_master_top.v
add_fileset_file i2c_timescale.v VERILOG_INCLUDE PATH i2c_timescale.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true

add_interface_port clock csi_clk clk Input 1


# 
# connection point clock_reset
# 
add_interface clock_reset reset end
set_interface_property clock_reset associatedClock clock
set_interface_property clock_reset synchronousEdges DEASSERT
set_interface_property clock_reset ENABLED true

add_interface_port clock_reset csi_reset_n reset_n Input 1


# 
# connection point irq
# 
add_interface irq interrupt end
set_interface_property irq associatedAddressablePoint avalon_slave
set_interface_property irq associatedClock clock
set_interface_property irq associatedReset clock_reset
set_interface_property irq ENABLED true

add_interface_port irq avs_irq irq Output 1


# 
# connection point avalon_slave
# 
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressUnits WORDS
set_interface_property avalon_slave associatedClock clock
set_interface_property avalon_slave associatedReset clock_reset
set_interface_property avalon_slave bitsPerSymbol 8
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave burstcountUnits WORDS
set_interface_property avalon_slave explicitAddressSpan 0
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 0
set_interface_property avalon_slave readLatency 0
set_interface_property avalon_slave readWaitTime 1
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave writeWaitTime 0
set_interface_property avalon_slave ENABLED true

add_interface_port avalon_slave avs_address address Input 3
add_interface_port avalon_slave avs_writedata writedata Input 8
add_interface_port avalon_slave avs_readdata readdata Output 8
add_interface_port avalon_slave avs_read read Input 1
add_interface_port avalon_slave avs_write write Input 1
add_interface_port avalon_slave avs_waitrequest waitrequest Output 1
set_interface_assignment avalon_slave embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point conduit_i2c
# 
add_interface conduit_i2c conduit end
set_interface_property conduit_i2c associatedClock ""
set_interface_property conduit_i2c associatedReset ""
set_interface_property conduit_i2c ENABLED true

add_interface_port conduit_i2c coe_i2c_scl_oe_n export Output 1
add_interface_port conduit_i2c coe_i2c_scl_o export Output 1
add_interface_port conduit_i2c coe_i2c_scl_i export Input 1
add_interface_port conduit_i2c coe_i2c_sda_i export Input 1
add_interface_port conduit_i2c coe_i2c_sda_oe_n export Output 1
add_interface_port conduit_i2c coe_i2c_sda_o export Output 1

