# TCL File Generated by Component Editor 13.1
# Wed Sep 10 14:59:48 BST 2014
# DO NOT MODIFY


# 
# ReconfigPLL "ReconfigPLL" v1.0
# Simon Moore 2014.09.10.14:59:48
# Reconfigurable PLL
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module ReconfigPLL
# 
set_module_property DESCRIPTION "Reconfigurable PLL"
set_module_property NAME ReconfigPLL
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Cheri_Video
set_module_property AUTHOR "Simon Moore"
set_module_property DISPLAY_NAME ReconfigPLL
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL reconfig_pll
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file reconfig_pll.sv SYSTEM_VERILOG PATH reconfig_pll.sv TOP_LEVEL_FILE
add_fileset_file reconfig_megafunction_pll_reconfig.v VERILOG PATH reconfig_megafunction_pll_reconfig.v
add_fileset_file reconfig_megafunction_pll.v VERILOG PATH reconfig_megafunction_pll.v
add_fileset_file reconfig_megafunction_pll.mif MIF PATH reconfig_megafunction_pll.mif


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock_avs
# 
add_interface clock_avs clock end
set_interface_property clock_avs clockRate 0
set_interface_property clock_avs ENABLED true
set_interface_property clock_avs EXPORT_OF ""
set_interface_property clock_avs PORT_NAME_MAP ""
set_interface_property clock_avs CMSIS_SVD_VARIABLES ""
set_interface_property clock_avs SVD_ADDRESS_GROUP ""

add_interface_port clock_avs csi_clk_clock clk Input 1


# 
# connection point clock_avs_reset
# 
add_interface clock_avs_reset reset end
set_interface_property clock_avs_reset associatedClock clock_avs
set_interface_property clock_avs_reset synchronousEdges DEASSERT
set_interface_property clock_avs_reset ENABLED true
set_interface_property clock_avs_reset EXPORT_OF ""
set_interface_property clock_avs_reset PORT_NAME_MAP ""
set_interface_property clock_avs_reset CMSIS_SVD_VARIABLES ""
set_interface_property clock_avs_reset SVD_ADDRESS_GROUP ""

add_interface_port clock_avs_reset csi_clk_reset reset Input 1


# 
# connection point clock_ref_pin
# 
add_interface clock_ref_pin clock end
set_interface_property clock_ref_pin clockRate 0
set_interface_property clock_ref_pin ENABLED true
set_interface_property clock_ref_pin EXPORT_OF ""
set_interface_property clock_ref_pin PORT_NAME_MAP ""
set_interface_property clock_ref_pin CMSIS_SVD_VARIABLES ""
set_interface_property clock_ref_pin SVD_ADDRESS_GROUP ""

add_interface_port clock_ref_pin csi_clkpin_clock clk Input 1


# 
# connection point avalon_slave
# 
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressUnits WORDS
set_interface_property avalon_slave associatedClock clock_avs
set_interface_property avalon_slave associatedReset clock_avs_reset
set_interface_property avalon_slave bitsPerSymbol 8
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave burstcountUnits WORDS
set_interface_property avalon_slave explicitAddressSpan 0
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 0
set_interface_property avalon_slave readLatency 0
set_interface_property avalon_slave readWaitTime 1
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave writeWaitTime 0
set_interface_property avalon_slave ENABLED true
set_interface_property avalon_slave EXPORT_OF ""
set_interface_property avalon_slave PORT_NAME_MAP ""
set_interface_property avalon_slave CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave avs_address address Input 8
add_interface_port avalon_slave avs_writedata writedata Input 32
add_interface_port avalon_slave avs_readdata readdata Output 32
add_interface_port avalon_slave avs_read read Input 1
add_interface_port avalon_slave avs_write write Input 1
add_interface_port avalon_slave avs_waitrequest waitrequest Output 1
set_interface_assignment avalon_slave embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clock_reconfig_source
# 
add_interface clock_reconfig_source clock start
set_interface_property clock_reconfig_source associatedDirectClock ""
set_interface_property clock_reconfig_source clockRate 200
set_interface_property clock_reconfig_source clockRateKnown true
set_interface_property clock_reconfig_source ENABLED true
set_interface_property clock_reconfig_source EXPORT_OF ""
set_interface_property clock_reconfig_source PORT_NAME_MAP ""
set_interface_property clock_reconfig_source CMSIS_SVD_VARIABLES ""
set_interface_property clock_reconfig_source SVD_ADDRESS_GROUP ""

add_interface_port clock_reconfig_source cso_reconfigclk_clock clk Output 1


# 
# connection point clock_reconfig_source_reset
# 
add_interface clock_reconfig_source_reset reset start
set_interface_property clock_reconfig_source_reset associatedClock clock_reconfig_source
set_interface_property clock_reconfig_source_reset associatedDirectReset ""
set_interface_property clock_reconfig_source_reset associatedResetSinks ""
set_interface_property clock_reconfig_source_reset synchronousEdges DEASSERT
set_interface_property clock_reconfig_source_reset ENABLED true
set_interface_property clock_reconfig_source_reset EXPORT_OF ""
set_interface_property clock_reconfig_source_reset PORT_NAME_MAP ""
set_interface_property clock_reconfig_source_reset CMSIS_SVD_VARIABLES ""
set_interface_property clock_reconfig_source_reset SVD_ADDRESS_GROUP ""

add_interface_port clock_reconfig_source_reset cso_reconfigclk_reset_n reset_n Output 1

