# TCL File Generated by Component Editor 13.1
# Wed Jan 20 20:33:20 GMT 2016
# DO NOT MODIFY


# 
# JTAGAtlantic2Stream "JTAG Atlantic to Stream" v1.0
# Theo Markettos 2016.01.20.20:33:20
# Interfaces to Altera JTAG UART to turn it into a stream via Atlantic interface
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module JTAGAtlantic2Stream
# 
set_module_property DESCRIPTION "Interfaces to Altera JTAG UART to turn it into a stream via Atlantic interface"
set_module_property NAME JTAGAtlantic2Stream
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Cheri_IO
set_module_property AUTHOR "Theo Markettos"
set_module_property DISPLAY_NAME "JTAG Atlantic to Stream"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL mkJTAGAtlantic2Stream
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file mkJTAGAtlantic2Stream.v VERILOG PATH mkJTAGAtlantic2Stream.v TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter jtag_uart_instance_id STD_LOGIC_VECTOR 0 "Instance ID to supply to nios2-terminal"
set_parameter_property jtag_uart_instance_id DEFAULT_VALUE 0
set_parameter_property jtag_uart_instance_id DISPLAY_NAME jtag_uart_instance_id
set_parameter_property jtag_uart_instance_id WIDTH 9
set_parameter_property jtag_uart_instance_id TYPE STD_LOGIC_VECTOR
set_parameter_property jtag_uart_instance_id UNITS None
set_parameter_property jtag_uart_instance_id ALLOWED_RANGES 0:511
set_parameter_property jtag_uart_instance_id DESCRIPTION "Instance ID to supply to nios2-terminal"
set_parameter_property jtag_uart_instance_id HDL_PARAMETER true


# 
# display items
# 
add_display_item "JTAG Interface settings" jtag_uart_instance_id PARAMETER ""


# 
# connection point clockreset
# 
add_interface clockreset clock end
set_interface_property clockreset clockRate 0
set_interface_property clockreset ENABLED true
set_interface_property clockreset EXPORT_OF ""
set_interface_property clockreset PORT_NAME_MAP ""
set_interface_property clockreset CMSIS_SVD_VARIABLES ""
set_interface_property clockreset SVD_ADDRESS_GROUP ""

add_interface_port clockreset csi_clockreset_clk clk Input 1


# 
# connection point clockreset_reset
# 
add_interface clockreset_reset reset end
set_interface_property clockreset_reset associatedClock clockreset
set_interface_property clockreset_reset synchronousEdges DEASSERT
set_interface_property clockreset_reset ENABLED true
set_interface_property clockreset_reset EXPORT_OF ""
set_interface_property clockreset_reset PORT_NAME_MAP ""
set_interface_property clockreset_reset CMSIS_SVD_VARIABLES ""
set_interface_property clockreset_reset SVD_ADDRESS_GROUP ""

add_interface_port clockreset_reset csi_clockreset_reset_n reset_n Input 1


# 
# connection point stream_in
# 
add_interface stream_in avalon_streaming end
set_interface_property stream_in associatedClock clockreset
set_interface_property stream_in associatedReset clockreset_reset
set_interface_property stream_in dataBitsPerSymbol 8
set_interface_property stream_in errorDescriptor ""
set_interface_property stream_in firstSymbolInHighOrderBits true
set_interface_property stream_in maxChannel 0
set_interface_property stream_in readyLatency 0
set_interface_property stream_in ENABLED true
set_interface_property stream_in EXPORT_OF ""
set_interface_property stream_in PORT_NAME_MAP ""
set_interface_property stream_in CMSIS_SVD_VARIABLES ""
set_interface_property stream_in SVD_ADDRESS_GROUP ""

add_interface_port stream_in asi_stream_in_data data Input 8
add_interface_port stream_in asi_stream_in_valid valid Input 1
add_interface_port stream_in asi_stream_in_ready ready Output 1


# 
# connection point stream_out
# 
add_interface stream_out avalon_streaming start
set_interface_property stream_out associatedClock clockreset
set_interface_property stream_out associatedReset clockreset_reset
set_interface_property stream_out dataBitsPerSymbol 8
set_interface_property stream_out errorDescriptor ""
set_interface_property stream_out firstSymbolInHighOrderBits true
set_interface_property stream_out maxChannel 0
set_interface_property stream_out readyLatency 0
set_interface_property stream_out ENABLED true
set_interface_property stream_out EXPORT_OF ""
set_interface_property stream_out PORT_NAME_MAP ""
set_interface_property stream_out CMSIS_SVD_VARIABLES ""
set_interface_property stream_out SVD_ADDRESS_GROUP ""

add_interface_port stream_out aso_stream_out_data data Output 8
add_interface_port stream_out aso_stream_out_valid valid Output 1
add_interface_port stream_out aso_stream_out_ready ready Input 1



