/*-
 * Copyright (c) 2012 Robert N. M. Watson
 * All rights reserved.
 *
 * This software was developed by SRI International and the University of
 * Cambridge Computer Laboratory under DARPA/AFRL contract FA8750-10-C-0237
 * ("CTSRD"), as part of the DARPA CRASH research programme.
 *
 * @BERI_LICENSE_HEADER_START@
 *
 * Licensed to BERI Open Systems C.I.C. (BERI) under one or more contributor
 * license agreements.  See the NOTICE file distributed with this work for
 * additional information regarding copyright ownership.  BERI licenses this
 * file to you under the BERI Hardware-Software License, Version 1.0 (the
 * "License"); you may not use this file except in compliance with the
 * License.  You may obtain a copy of the License at:
 *
 *   http://www.beri-open-systems.org/legal/license-1-0.txt
 *
 * Unless required by applicable law or agreed to in writing, Work distributed
 * under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
 * CONDITIONS OF ANY KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations under the License.
 *
 * @BERI_LICENSE_HEADER_END@
 */

/*-
 * CHERI bus configuration parameters for PISM.
 *
 * WARNING:  Historically, this file was automatically generated by
 * tools/cheri_genfiles.py, extracting parameters from the Altera project
 * configuration.  THIS IS NO LONGER TRUE.
 *
 * The following are physical addresses as configured on CHERI's bus, and are
 * intended for short-term use in PISM while we complete work on dynamic
 * configuration.  If they are used in software intended to run *on* CHERI,
 * then they should be translated to virtual addresses using the macros below.
 * 
 *
 * In the future, we will want to have most of these passed from hardware to
 * software using FDT, and avoid hard-coding them.
 */

#ifndef _PISM_PARAMETERS_H_
#define	_PISM_PARAMETERS_H_

#define	MIPS_XKPHYS_UNCACHED_BASE	0x9000000000000000
#define	MIPS_XKPHYS_CACHED_NC_BASE	0x9800000000000000

#define	MIPS_PHYS_TO_CACHED(phys)	((phys) | MIPS_XKPHYS_CACHED_NC_BASE)
#define	MIPS_PHYS_TO_UNCACHED(phys)	((phys) | MIPS_XKPHYS_UNCACHED_BASE)

#define	CHERI_JTAG_UART_BASE		0x7f000000
#define	CHERI_LOOPBACK_UART_BASE	0x7f001000
#define	CHERI_NET_TX			0x7f002000
#define	CHERI_NET_RX			0x7f003000
#define	CHERI_COUNT			0x7f800000
#define	CHERI_DEBUG_JTAG_UART_BASE	0x7f005000
#define	CHERI_LEDS			0x7f006000
#define	CHERI_FRAMEBUF_BASE		0x04000000
#define	CHERI_TOUCHSCREEN_BASE		0x05000000
#define	CHERI_COMPOSITOR_BASE		0x7f80d000
#define	CHERI_COMPOSITOR_MEM_BASE	0x20000000
#define	CHERI_COMPOSITOR_MEM_LENGTH	0x10000000

#endif /* _PISM_PARAMETERS_H_ */
