# TCL File Generated by Component Editor 12.1
# Tue Dec 18 15:32:52 GMT 2012
# DO NOT MODIFY


# 
# FanControl50MHz "Fan Control 50MHz" v1.0
# Simon Moore 2012.12.18.15:32:52
# Fan Controller for DE4 board
# 

# 
# request TCL package from ACDS 12.1
# 
package require -exact qsys 12.1


# 
# module FanControl50MHz
# 
set_module_property DESCRIPTION "Fan Controller for DE4 board"
set_module_property NAME FanControl50MHz
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Cheri_IO
set_module_property AUTHOR "Simon Moore"
set_module_property DISPLAY_NAME "Fan Control 50MHz"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL mkFanControl50MHz
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file mkFanControl50MHz.v VERILOG PATH mkFanControl50MHz.v
add_fileset_file temp_sense.v VERILOG PATH temp_sense.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clockreset
# 
add_interface clockreset clock end
set_interface_property clockreset clockRate 0
set_interface_property clockreset ENABLED true

add_interface_port clockreset csi_clockreset_clk clk Input 1


# 
# connection point clockreset_reset
# 
add_interface clockreset_reset reset end
set_interface_property clockreset_reset associatedClock clockreset
set_interface_property clockreset_reset synchronousEdges DEASSERT
set_interface_property clockreset_reset ENABLED true

add_interface_port clockreset_reset csi_clockreset_reset_n reset_n Input 1


# 
# connection point s0
# 
add_interface s0 avalon end
set_interface_property s0 addressUnits WORDS
set_interface_property s0 associatedClock clockreset
set_interface_property s0 associatedReset clockreset_reset
set_interface_property s0 bitsPerSymbol 8
set_interface_property s0 burstOnBurstBoundariesOnly false
set_interface_property s0 burstcountUnits WORDS
set_interface_property s0 explicitAddressSpan 0
set_interface_property s0 holdTime 0
set_interface_property s0 linewrapBursts false
set_interface_property s0 maximumPendingReadTransactions 0
set_interface_property s0 readLatency 0
set_interface_property s0 readWaitTime 1
set_interface_property s0 setupTime 0
set_interface_property s0 timingUnits Cycles
set_interface_property s0 writeWaitTime 0
set_interface_property s0 ENABLED true

add_interface_port s0 avs_s0_address address Input 1
add_interface_port s0 avs_s0_writedata writedata Input 32
add_interface_port s0 avs_s0_write write Input 1
add_interface_port s0 avs_s0_read read Input 1
add_interface_port s0 avs_s0_byteenable byteenable Input 4
add_interface_port s0 avs_s0_readdata readdata Output 32
add_interface_port s0 avs_s0_waitrequest waitrequest Output 1
set_interface_assignment s0 embeddedsw.configuration.isFlash 0
set_interface_assignment s0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment s0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment s0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point fancontrol
# 
add_interface fancontrol conduit end
set_interface_property fancontrol associatedClock clockreset
set_interface_property fancontrol associatedReset clockreset_reset
set_interface_property fancontrol ENABLED true

add_interface_port fancontrol coe_fan_on_pwm export Output 1
add_interface_port fancontrol coe_temp_lower_seg_n export Output 7
add_interface_port fancontrol coe_temp_upper_seg_n export Output 7

