#!/bin/sh
#-
# Copyright (c) 2011 Wojciech A. Koszek
# Copyright (c) 2011 Jonathan Woodruff
# All rights reserved.
#
# This software was developed by SRI International and the University of
# Cambridge Computer Laboratory under DARPA/AFRL contract FA8750-10-C-0237
# ("CTSRD"), as part of the DARPA CRASH research programme.
#
# @BERI_LICENSE_HEADER_START@
#
# Licensed to BERI Open Systems C.I.C. (BERI) under one or more contributor
# license agreements.  See the NOTICE file distributed with this work for
# additional information regarding copyright ownership.  BERI licenses this
# file to you under the BERI Hardware-Software License, Version 1.0 (the
# "License"); you may not use this file except in compliance with the
# License.  You may obtain a copy of the License at:
#
#   http://www.beri-open-systems.org/legal/license-1-0.txt
#
# Unless required by applicable law or agreed to in writing, Work distributed
# under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
# CONDITIONS OF ANY KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations under the License.
#
# @BERI_LICENSE_HEADER_END@
#

if [ "X$1" = "X" ]; then
	echo Pass at least one file.
	exit 1;
fi

FIRST=1
svn log $1 | grep ^r | cut -d " " -f 1 | tac | while read REV; do
	#echo % Reading $REV
	if [ $FIRST -eq 1 ]; then
		PREV=$REV
		FIRST=0
		#echo % First PREV=$PREV FIRST=$FIRST
	else
		CURR=$REV
		echo "********************** Printing differences in $1 between $PREV and $CURR revision *********************************************"
		echo % svn diff -r $PREV:$CURR
		svn log -r $CURR
		svn diff -r $PREV:$CURR
		echo "********************************************************************************************************************************"
		PREV=$CURR
		echo "********************************************************************************************************************************"
	fi
done
